{% set name = "rubin-sim-all" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsst/rubin_sim/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 834db8396a0dd0c45cf83ccdc3a2052759b6a1e5a95c0990971350821c6fcdb0

build:
  number: 1
  skip: true  # [win]

outputs:
  - name: rubin_sim
    version: {{ version }}
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('rubin-sim', exact=True) }}
    test:
      imports:
        - rubin_sim

  - name: rubin-sim
    version: {{ version }}
    script: run_sim_build.sh
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
        - setuptools_scm <8.0
        - setuptools_scm_git_archive
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - matplotlib-base
        - healpy
        - pandas
        - pyarrow
        - numexpr
        - scipy
        - sqlalchemy
        - astropy-base
        - h5py
        - openorb
        - openorb-data-de405
        - astroplan
        - george
        - pytables
        - colorcet
        - cycler
        - scikit-learn
        - shapely
        - skyfield
        - skyproj
        - tqdm
        - rubin-scheduler
    test:
      imports:
        - rubin_sim
      commands:
        - scheduler_download_data --help

about:
  home: https://github.com/lsst/rubin_sim
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Scheduler, survey strategy analysis, and other simulation tools for Rubin Observatory.

extra:
  recipe-maintainers:
    - tribeiro
    - rhiannonlynne
    - beckermr
    - yoachim
