{% set name = "rubin-sim-all" %}
{% set version = "2.2.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsst/rubin_sim/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 30f3f1639f76e52801d3b7195855c8be9a676068a193e76ae2866506b611a35e

build:
  number: 0

outputs:
  - name: rubin_sim
    version: {{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('rubin-sim', exact=True) }}
    test:
      imports:
        - rubin_sim
      requires:
        - python {{ python_min }}

  - name: rubin-sim
    version: {{ version }}
    script: run_sim_build.sh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm >=8.0
        - setuptools_scm_git_archive
      run:
        - python >={{ python_min }}
        - numpy
        - matplotlib-base
        - healpy
        - pandas
        - pyarrow
        - numexpr
        - scipy
        - sqlalchemy
        - astropy-base
        - h5py
        - astroplan
        - george
        - pytables
        - colorcet
        - cycler
        - scikit-learn
        - shapely
        - skyfield
        - skyproj
        - tqdm
        - gitpython
        - conda
        - rubin-scheduler
    test:
      imports:
        - rubin_sim
      commands:
        - scheduler_download_data --help
      requires:
        - python {{ python_min }}

about:
  home: https://github.com/lsst/rubin_sim
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Scheduler, survey strategy analysis, and other simulation tools for Rubin Observatory.

extra:
  recipe-maintainers:
    - roceb
    - tribeiro
    - rhiannonlynne
    - beckermr
    - yoachim
